// <auto-generated />
namespace SocialMediaApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deleted_Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleted_Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301606307_Deleted_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
